MIN_LATITUDE = -90
MAX_LATITUDE = 90
MIN_LONGITUDE = -180
MAX_LONGITUDE = 180

AUTOPILOT_SERIAL_PORT = "/dev/ttyTHS1"
AUTOPILOT_BAUDRATE = 115200
GCS_SERIAL_PORT = ""
GCS_BAUDRATE = 0
HEARTBEAT = "HEARTBEAT"
AUTOPILOT_HEARTBEAT_TIMEOUT = 5
GCS_HEARTBEAT_TIMEOUT = 5
HEARTBEAT_TIMEOUT = 2


def valid_latitude_and_longitude(lat, lon):
    if lat < MIN_LATITUDE or lat > MAX_LATITUDE:
        return False
    if lon < MIN_LONGITUDE or lon > MAX_LONGITUDE:
        return False
    return True
